import { profile, skills, experiences, resumes, filters } from '../data/content.mjs';
import { projects } from '../data/github.mjs';
import { escape as e, date, external } from '../utils/html.mjs';
import { icon } from './icons.mjs';
import { artwork } from './art.mjs';

export const header = () => `<a class="skip-link" href="#main">Aller au contenu</a><header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Accueil — ${e(profile.name)}"><span class="brand-mark">${e(profile.initials)}<i></i></span><span>${e(profile.name.trim().split(/\s+/).at(-1).toUpperCase())}<span class="brand-sub">PORTFOLIO TECHNIQUE</span></span></a><nav class="main-nav" id="navigation" aria-label="Navigation principale"><a href="/#projets">Projets</a><a href="/#profil">Profil</a><a href="/#parcours">Parcours</a><a href="/#cv">CV</a><a class="nav-contact" href="/#contact">Contact</a></nav><div class="header-controls"><button class="icon-button" id="theme-toggle" aria-label="Activer le thème sombre">${icon('sun')}<span class="sr-only">Changer de thème</span></button><button class="icon-button menu-toggle" id="menu-toggle" aria-label="Ouvrir le menu" aria-expanded="false" aria-controls="navigation">${icon('menu')}</button></div></div></header>`;

export const footer = () => `<footer class="site-footer container"><a class="footer-name" href="/">${e(profile.name)}</a><span>Du matériel aux idées.</span><a href="#main">Retour en haut</a></footer>`;

export function card(p, index) {
  const search = `${p.title} ${p.category} ${p.summary} ${p.tags.join(' ')} ${p.language}`.toLocaleLowerCase('fr');
  return `<article class="project-card tone-${index % 4}" data-categories="${e(JSON.stringify(p.filters))}" data-search="${e(search)}"><div class="card-top"><span class="project-category">${e(p.category)}</span><span class="project-number">${String(index + 1).padStart(2, '0')}</span></div><div class="card-content"><h3><a href="/projets/${e(p.id)}/">${e(p.title)}</a></h3><p>${e(p.summary)}</p></div><div class="card-art">${artwork(p.id, `card-${p.id}`)}</div><div class="tags">${p.tags.map(t => `<span>${e(t)}</span>`).join('')}</div><div class="card-footer"><span>${p.visibility === 'public' ? 'Code public' : p.visibility === 'private' ? 'Présentation du projet' : 'Projet universitaire'}</span><a href="/projets/${e(p.id)}/" aria-label="Découvrir le projet : ${e(p.title)}"><span>Découvrir</span><span class="round-arrow" aria-hidden="true">↗</span></a></div></article>`;
}

export const hero = () => `<section class="hero container" aria-labelledby="hero-title"><div class="hero-overline"><span>${e(profile.name)}</span><a href="#contact"><i></i>À la recherche d’une alternance</a></div><div class="hero-copy"><p class="eyebrow">Systèmes embarqués. IoT. Intelligence artificielle.</p><h1 id="hero-title">${e(profile.headline[0])}<br><span>${e(profile.headline[1])}</span></h1><p class="hero-description">${e(profile.introduction)}</p><div class="hero-actions"><a class="button primary" href="#projets">Explorer mes projets</a><a class="text-link" href="#cv">Découvrir mes CV <span aria-hidden="true">›</span></a></div></div><div class="hero-stage"><div class="stage-orbit orbit-one"></div><div class="stage-orbit orbit-two"></div><div class="hero-chip">${artwork('hero','hero')}</div><span class="stage-label label-one">Capteurs.<br><strong>Observer le réel.</strong></span><span class="stage-label label-two">Algorithmes.<br><strong>Donner du sens.</strong></span><div class="stage-caption"><span>Du matériel aux idées.</span><span>Illustration conceptuelle</span></div></div><div class="domain-strip"><a href="#projets" data-domain="Systèmes embarqués">${icon('chip')}<span>Embarqué</span></a><a href="#projets" data-domain="IoT">${icon('signal')}<span>Objets connectés</span></a><a href="#projets" data-domain="Intelligence artificielle">${icon('nodes')}<span>Intelligence artificielle</span></a><a href="#projets" data-domain="Web">${icon('code')}<span>Logiciel & web</span></a></div></section>`;

export const projectSection = () => `<section id="projets" class="section container"><div class="section-heading"><div><p class="eyebrow">01 / RÉALISATIONS</p><h2>Explorez mes projets.<br><span>Du concret. À chaque étape.</span></h2></div><p>Du bas niveau aux interfaces, une sélection de travaux qui reflètent ma pratique.</p></div><div class="project-toolbar" hidden><div class="filters" role="group" aria-label="Filtrer les projets par domaine">${filters.map((f, i) => `<button class="filter ${i === 0 ? 'active' : ''}" data-filter="${e(f)}" aria-pressed="${i === 0}">${e(f)}</button>`).join('')}</div><div class="project-search">${icon('search')}<label class="sr-only" for="project-search">Rechercher un projet</label><input id="project-search" type="search" placeholder="Rechercher un projet" autocomplete="off"></div></div><div class="project-results" hidden><span id="results-count" aria-live="polite">${projects.length} projets</span><button id="reset-filters" hidden>Réinitialiser les filtres</button></div><div class="project-grid project-gallery" id="project-gallery" tabindex="0" aria-label="Galerie des projets">${projects.map(card).join('')}</div><div class="gallery-controls" hidden><p>Des illustrations pour explorer mes univers.</p><div><button class="gallery-prev icon-button" aria-label="Voir les projets précédents">←</button><button class="gallery-next icon-button" aria-label="Voir les projets suivants">→</button></div></div><div id="empty-projects" class="empty-projects" hidden><h3>Aucun projet dans cette sélection</h3><p>Essayez un autre domaine ou effacez votre recherche.</p><button class="button secondary" id="empty-reset">Afficher tous les projets</button></div><p class="project-disclosure">Les projets privés sont présentés ici ; leur code n’est pas accessible publiquement. Les détails de chaque réalisation précisent les éléments disponibles.</p></section>`;

export const profileSection = () => `<section id="profil" class="profile-section"><div class="container profile-layout"><div><p class="eyebrow">02 / PROFIL</p><h2>Comprendre le système.<br><span>Construire la solution.</span></h2></div><div class="profile-body"><p>${e(profile.about)}</p><p>Ma démarche : comprendre le besoin, organiser le code et relier chaque choix technique à un usage concret.</p><div class="profile-facts"><div><span>FORMATION ACTUELLE</span><strong>${e(profile.currentStudy)}</strong></div><div><span>ANCRAGE</span><strong>${e(profile.location)}</strong></div></div>${profile.github ? `${external(profile.github)}<span class="text-link">${icon('github')} Consulter mon GitHub</span></a>` : ''}</div></div></section>`;

export const skillsSection = () => `<section id="competences" class="section container"><div class="section-heading"><div><p class="eyebrow">03 / COMPÉTENCES</p><h2>Une pratique<br><span>à plusieurs échelles.</span></h2></div><p>Des niveaux indicatifs, fondés sur les technologies utilisées dans mes projets.</p></div><div class="skills-grid">${skills.map(s => `<article class="skill-card"><div class="skill-heading">${icon(s.icon)}<h3>${e(s.title)}</h3></div><p>${e(s.description)}</p><ul>${s.items.map(([name, level]) => `<li><span>${e(name)}</span><span class="skill-level">${e(level)}</span></li>`).join('')}</ul></article>`).join('')}</div></section>`;

export const experienceSection = () => `<section id="parcours" class="timeline-section"><div class="container timeline-layout"><div class="timeline-intro"><p class="eyebrow">04 / PARCOURS</p><h2>Apprendre.<br>Expérimenter.<br><span>Progresser.</span></h2><p>Une formation en informatique, prolongée par les systèmes embarqués et les objets connectés.</p></div><ol class="timeline">${experiences.map(x => `<li><span class="timeline-dot"></span><div class="timeline-meta"><span>${e(x.period)}</span><span class="timeline-kind">${e(x.kind)}${x.status ? ` · ${e(x.status)}` : ''}</span></div><h3>${e(x.title)}</h3><p class="timeline-org">${e(x.organization)}</p><p>${e(x.description)}</p>${x.technologies?.length ? `<div class="tags">${x.technologies.map(t => `<span>${e(t)}</span>`).join('')}</div>` : ''}${x.link ? `${external(x.link)}<span class="text-link">En savoir plus</span></a>` : ''}</li>`).join('')}</ol></div></section>`;

export const cvSection = () => `<section id="cv" class="section container cv-section"><div><p class="eyebrow">05 / CURRICULUM VITAE</p><h2>Deux regards.<br><span>Un même parcours.</span></h2><p>Un aperçu de ma formation, de mes expériences et de mes réalisations.</p></div><div class="cv-list">${resumes.filter(x => x.path).map(x => `<article class="cv-card">${icon('download')}<div><span class="mono">CV / PDF</span><h3>${e(x.title)}</h3><p>${e(x.description)}</p><a class="button primary" href="${e(x.path)}" download>Télécharger le CV<span class="sr-only"> ${e(x.title)}</span></a><a class="cv-preview" href="${e(x.path)}" target="_blank" rel="noopener noreferrer">Consulter le PDF</a></div></article>`).join('') || `<div class="cv-card"><p>Mon CV est disponible sur demande.</p></div>`}</div></section>`;

export const contactSection = () => `<section id="contact" class="contact-section"><div class="container"><div class="contact-top"><div><p class="eyebrow">06 / CONTACT</p><h2>Votre prochain projet<br><span>commence par un échange.</span></h2></div>${profile.opportunities.active ? `<div class="opportunity"><span class="mono">OPPORTUNITÉS</span><p>${e(profile.opportunities.text)}</p><div class="opportunity-types">${profile.opportunities.types.map(t => `<span class="${t === profile.opportunities.priority ? 'priority' : ''}">${e(t)}</span>`).join('')}</div></div>` : ''}</div><div class="opportunity-domains">${profile.opportunities.domains.map(d => `<span>${e(d)}</span>`).join('')}</div><div class="contact-bottom"><div>${profile.email ? `<a class="contact-email" href="mailto:${e(profile.email)}">${e(profile.email)}</a><button class="copy-email" data-email="${e(profile.email)}" aria-label="Copier l’adresse email">${icon('copy')}</button><span class="sr-only" id="copy-status" role="status"></span>` : ''}<p>${e(profile.location)}</p></div><div class="contact-links">${profile.github ? `${external(profile.github)}${icon('github')} GitHub</a>` : ''}${profile.linkedin ? `${external(profile.linkedin)}LinkedIn</a>` : ''}</div></div></div></section>`;

export const home = () => `${header()}<main id="main">${hero()}${projectSection()}${profileSection()}${skillsSection()}${experienceSection()}${cvSection()}${contactSection()}</main>${footer()}`;

export function detail(p) {
  return `${header()}<main id="main" class="container detail-page"><a class="back-link" href="/#projets">Tous les projets</a><div class="detail-heading"><div class="eyebrow">${e(p.category)}</div><h1>${e(p.title)}</h1><p>${e(p.description)}</p><div class="tags">${p.tags.map(t => `<span>${e(t)}</span>`).join('')}</div></div><div class="detail-layout"><div><section class="detail-features"><h2>Ce que j’ai travaillé</h2><ul>${p.highlights.map(h => `<li>${e(h)}</li>`).join('')}</ul></section>${p.image ? `<figure class="detail-image"><img src="${e(p.image)}" alt="${e(p.imageAlt)}" width="700" height="454" loading="lazy"><figcaption>${e(p.imageCaption)}</figcaption></figure>` : ''}<div class="detail-note"><h2>Contexte du projet</h2><p>${e(p.note)}</p></div></div><aside class="detail-aside" aria-label="Informations du projet"><dl><div><dt>Cadre</dt><dd>${e(p.status)}</dd></div>${p.language ? `<div><dt>Langage principal</dt><dd>${e(p.language)}</dd></div>` : ''}${p.updatedAt ? `<div><dt>Dernière mise à jour du dépôt</dt><dd><time datetime="${e(p.updatedAt)}">${date(p.updatedAt)}</time></dd></div>` : ''}<div><dt>Accès au code</dt><dd>${p.visibility === 'public' ? 'Dépôt public' : p.visibility === 'private' ? 'Dépôt privé' : 'Code non publié'}</dd></div></dl>${p.github ? `${external(p.github)}<span class="button primary">${icon('github')} Voir le code sur GitHub</span></a>` : `<a class="button secondary" href="mailto:${e(profile.email)}?subject=${encodeURIComponent(`Échange au sujet du projet ${p.title}`)}">Échanger sur ce projet</a>`}${p.demo ? `${external(p.demo)}<span class="button secondary">Voir la démonstration</span></a>` : ''}<p class="source-note">${p.visibility !== 'unpublished' ? 'Présentation fondée sur la documentation et les fichiers du dépôt.' : 'Présentation fondée sur le CV existant.'}</p></aside></div><div class="detail-other"><h2>Continuer l’exploration</h2><div class="project-grid">${projects.filter(x => x.id !== p.id).slice(0, 3).map(card).join('')}</div></div></main>${footer()}`;
}
export const notFound = () => `${header()}<main class="container section" id="main"><p class="eyebrow">404 / PAGE INTROUVABLE</p><h1>Revenons aux projets.</h1><p class="not-found-text">Cette page n’est pas disponible.</p><a class="button primary" href="/">Revenir au portfolio</a></main>${footer()}`;
