import { profile, skills, experiences, resumes, filters } from '../data/content.mjs';
import { projects } from '../data/github.mjs';
import { escape as e, date, external } from '../utils/html.mjs';
import { icon } from './icons.mjs';
import { artwork } from './art.mjs';

export const header = (current = '/') => `<a class="skip-link" href="#main">Aller au contenu</a><header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="Accueil — ${e(profile.name)}"><span class="brand-mark">${e(profile.initials)}<i></i></span><span>${e(profile.name.trim().split(/\s+/).at(-1).toUpperCase())}<span class="brand-sub">PORTFOLIO TECHNIQUE</span></span></a><nav class="main-nav" id="navigation" aria-label="Navigation principale">${[['/', 'Accueil'], ['/projets/', 'Projets'], ['/a-propos/', 'À propos'], ['/cv/', 'Mes CV']].map(([path, label]) => `<a href="${path}"${current === path ? ' aria-current="page"' : ''}>${label}</a>`).join('')}<a class="nav-contact" href="${current === '/projets/' ? '/#contact' : '#contact'}">Contact</a></nav><div class="header-controls"><button class="icon-button" id="theme-toggle" aria-label="Activer le thème sombre">${icon('sun')}<span class="sr-only">Changer de thème</span></button><button class="icon-button menu-toggle" id="menu-toggle" aria-label="Ouvrir le menu" aria-expanded="false" aria-controls="navigation">${icon('menu')}</button></div></div></header>`;

export const footer = () => `<footer class="site-footer container"><a class="footer-name" href="/">${e(profile.name)}</a><span>Du matériel aux idées.</span><a href="#main">Retour en haut</a></footer>`;

export function card(p, index) {
  const search = `${p.title} ${p.category} ${p.summary} ${p.tags.join(' ')} ${p.language}`.toLocaleLowerCase('fr');
  return `<article class="project-card tone-${index % 4}" data-categories="${e(JSON.stringify(p.filters))}" data-search="${e(search)}"><div class="card-top"><span class="project-category">${e(p.category)}</span><span class="project-number">${String(index + 1).padStart(2, '0')}</span></div><div class="card-content"><h3><a href="/projets/${e(p.id)}/">${e(p.title)}</a></h3><p>${e(p.summary)}</p></div><div class="card-art">${artwork(p.id, `card-${p.id}`)}</div><div class="tags">${p.tags.map(t => `<span>${e(t)}</span>`).join('')}</div><div class="card-footer"><span>${p.visibility === 'public' ? 'Code public' : p.visibility === 'private' ? 'Présentation du projet' : 'Projet universitaire'}</span><a href="/projets/${e(p.id)}/" aria-label="Découvrir le projet : ${e(p.title)}"><span>Découvrir</span><span class="round-arrow" aria-hidden="true">↗</span></a></div></article>`;
}

export const hero = () => `<section class="hero container" aria-labelledby="hero-title"><div class="hero-overline"><span>${e(profile.name)}</span><a href="#contact"><i></i>À la recherche d’une alternance</a></div><div class="hero-copy"><p class="eyebrow">Un parcours entre logiciel et objets connectés.</p><h1 id="hero-title">${e(profile.headline[0])}<br><span>${e(profile.headline[1])}</span></h1><p class="hero-description">${e(profile.introduction)}</p><div class="hero-actions"><a class="button primary" href="#projets">Voir ce que je construis</a><a class="text-link" href="#cv">Découvrir mes CV <span aria-hidden="true">›</span></a></div></div><div class="domain-strip"><a href="#projets" data-domain="Systèmes embarqués">${icon('chip')}<span>Embarqué</span></a><a href="#projets" data-domain="IoT">${icon('signal')}<span>Objets connectés</span></a><a href="#projets" data-domain="Intelligence artificielle">${icon('nodes')}<span>Intelligence artificielle</span></a><a href="#projets" data-domain="Web">${icon('code')}<span>Logiciel & web</span></a></div></section>`;

export const projectSection = (grid = false) => `<section id="projets" class="section container"><div class="section-heading"><div><p class="eyebrow">01 / RÉALISATIONS</p><h2>Ce que je construis.<br><span>Et comment je m’y prends.</span></h2></div><p>Chaque projet part d’une question concrète. Voici les outils et les choix techniques que j’ai explorés pour y répondre.</p></div><div class="project-toolbar" hidden><div class="filters" role="group" aria-label="Filtrer les projets par domaine">${filters.map((f, i) => `<button class="filter ${i === 0 ? 'active' : ''}" data-filter="${e(f)}" aria-pressed="${i === 0}">${e(f)}</button>`).join('')}</div><div class="project-search">${icon('search')}<label class="sr-only" for="project-search">Rechercher un projet</label><input id="project-search" type="search" placeholder="Rechercher un projet" autocomplete="off"></div></div><div class="project-results" hidden><span id="results-count" aria-live="polite">${projects.length} projets</span><button id="reset-filters" hidden>Réinitialiser les filtres</button></div><div class="project-grid ${grid ? 'project-directory' : 'project-gallery'}" ${grid ? '' : 'id="project-gallery" tabindex="0" aria-label="Galerie des projets"'}>${projects.map(card).join('')}</div><div class="gallery-controls" hidden><p>Des illustrations pour explorer mes univers.</p><div><button class="gallery-prev icon-button" aria-label="Voir les projets précédents">←</button><button class="gallery-next icon-button" aria-label="Voir les projets suivants">→</button></div></div><div id="empty-projects" class="empty-projects" hidden><h3>Aucun projet dans cette sélection</h3><p>Essayez un autre domaine ou effacez votre recherche.</p><button class="button secondary" id="empty-reset">Afficher tous les projets</button></div><p class="project-disclosure">Les projets privés sont présentés ici ; leur code n’est pas accessible publiquement. Les détails de chaque réalisation précisent les éléments disponibles.</p></section>`;

export const profileSection = () => `<section id="profil" class="profile-section"><div class="container profile-layout"><div><p class="eyebrow">02 / PROFIL</p><h2>Derrière les projets,<br><span>un parcours qui se construit.</span></h2></div><div class="profile-body"><p>${e(profile.about)}</p><p>J’aborde ces projets en partant du besoin : quelles données acquérir, comment les traiter et comment les rendre utilisables ? C’est ce lien entre le code et son usage que je cherche à comprendre.</p><div class="profile-facts"><div><span>FORMATION ACTUELLE</span><strong>${e(profile.currentStudy)}</strong></div><div><span>ANCRAGE</span><strong>${e(profile.location)}</strong></div></div>${profile.github ? `${external(profile.github)}<span class="text-link">${icon('github')} Consulter mon GitHub</span></a>` : ''}</div></div></section>`;

export const skillsSection = () => `<section id="competences" class="section container"><div class="section-heading"><div><p class="eyebrow">03 / COMPÉTENCES</p><h2>Une pratique<br><span>à plusieurs échelles.</span></h2></div><p>Des niveaux indicatifs, fondés sur les technologies utilisées dans mes projets.</p></div><div class="skills-grid">${skills.map(s => `<article class="skill-card"><div class="skill-heading">${icon(s.icon)}<h3>${e(s.title)}</h3></div><p>${e(s.description)}</p><ul>${s.items.map(([name, level]) => `<li><span>${e(name)}</span><span class="skill-level">${e(level)}</span></li>`).join('')}</ul></article>`).join('')}</div></section>`;

export const experienceSection = () => `<section id="parcours" class="timeline-section"><div class="container timeline-layout"><div class="timeline-intro"><p class="eyebrow">04 / PARCOURS</p><h2>Apprendre.<br>Expérimenter.<br><span>Progresser.</span></h2><p>Une formation en informatique, prolongée par les systèmes embarqués et les objets connectés.</p></div><ol class="timeline">${experiences.map(x => `<li><span class="timeline-dot"></span><div class="timeline-meta"><span>${e(x.period)}</span><span class="timeline-kind">${e(x.kind)}${x.status ? ` · ${e(x.status)}` : ''}</span></div><h3>${e(x.title)}</h3><p class="timeline-org">${e(x.organization)}</p><p>${e(x.description)}</p>${x.technologies?.length ? `<div class="tags">${x.technologies.map(t => `<span>${e(t)}</span>`).join('')}</div>` : ''}${x.link ? `${external(x.link)}<span class="text-link">En savoir plus</span></a>` : ''}</li>`).join('')}</ol></div></section>`;

export const cvSection = () => `<section id="cv" class="section container cv-section"><div><p class="eyebrow">05 / CURRICULUM VITAE</p><h2>Deux regards.<br><span>Un même parcours.</span></h2><p>Un aperçu de ma formation, de mes expériences et de mes réalisations.</p></div><div class="cv-list">${resumes.filter(x => x.path).map(x => `<article class="cv-card">${icon('download')}<div><span class="mono">CV / PDF</span><h3>${e(x.title)}</h3><p>${e(x.description)}</p><a class="button primary" href="${e(x.path)}" download>Télécharger le CV<span class="sr-only"> ${e(x.title)}</span></a><a class="cv-preview" href="${e(x.path)}" target="_blank" rel="noopener noreferrer">Consulter le PDF</a></div></article>`).join('') || `<div class="cv-card"><p>Mon CV est disponible sur demande.</p></div>`}</div></section>`;

export const contactSection = () => `<section id="contact" class="contact-section"><div class="container"><div class="contact-top"><div><p class="eyebrow">06 / CONTACT</p><h2>Parlons de votre équipe.<br><span>Et de ce que nous pourrions construire.</span></h2></div>${profile.opportunities.active ? `<div class="opportunity"><span class="mono">OPPORTUNITÉS</span><p>${e(profile.opportunities.text)}</p><div class="opportunity-types">${profile.opportunities.types.map(t => `<span class="${t === profile.opportunities.priority ? 'priority' : ''}">${e(t)}</span>`).join('')}</div></div>` : ''}</div><div class="opportunity-domains">${profile.opportunities.domains.map(d => `<span>${e(d)}</span>`).join('')}</div><div class="contact-bottom"><div>${profile.email ? `<a class="contact-email" href="mailto:${e(profile.email)}">${e(profile.email)}</a><button class="copy-email" data-email="${e(profile.email)}" aria-label="Copier l’adresse email">${icon('copy')}</button><span class="sr-only" id="copy-status" role="status"></span>` : ''}<p>${e(profile.location)}</p></div><div class="contact-links">${profile.github ? `${external(profile.github)}${icon('github')} GitHub</a>` : ''}${profile.linkedin ? `${external(profile.linkedin)}LinkedIn</a>` : ''}</div></div></div></section>`;

export const home = () => `${header()}<main id="main">${hero()}${storySection()}${projectSection()}${profileSection()}${journeyPreview()}${cvSection()}${contactSection()}</main>${footer()}`;

export function detail(p) {
  return `${header('/projets/')}<main id="main" class="container detail-page"><a class="back-link" href="/projets/">Tous les projets</a><div class="detail-heading"><div class="eyebrow">${e(p.category)}</div><h1>${e(p.title)}</h1><p>${e(p.description)}</p><div class="tags">${p.tags.map(t => `<span>${e(t)}</span>`).join('')}</div></div><div class="detail-layout"><div><section class="detail-features"><h2>Les choix techniques explorés</h2><ul>${p.highlights.map(h => `<li>${e(h)}</li>`).join('')}</ul></section>${p.image ? `<figure class="detail-image"><img src="${e(p.image)}" alt="${e(p.imageAlt)}" width="700" height="454" loading="lazy"><figcaption>${e(p.imageCaption)}</figcaption></figure>` : ''}<div class="detail-note"><h2>Contexte du projet</h2><p>${e(p.note)}</p></div></div><aside class="detail-aside" aria-label="Informations du projet"><dl><div><dt>Cadre</dt><dd>${e(p.status)}</dd></div>${p.language ? `<div><dt>Langage principal</dt><dd>${e(p.language)}</dd></div>` : ''}${p.updatedAt ? `<div><dt>Dernière mise à jour du dépôt</dt><dd><time datetime="${e(p.updatedAt)}">${date(p.updatedAt)}</time></dd></div>` : ''}<div><dt>Accès au code</dt><dd>${p.visibility === 'public' ? 'Dépôt public' : p.visibility === 'private' ? 'Dépôt privé' : 'Code non publié'}</dd></div></dl>${p.github ? `${external(p.github)}<span class="button primary">${icon('github')} Voir le code sur GitHub</span></a>` : `<a class="button secondary" href="mailto:${e(profile.email)}?subject=${encodeURIComponent(`Échange au sujet du projet ${p.title}`)}">Échanger sur ce projet</a>`}${p.demo ? `${external(p.demo)}<span class="button secondary">Voir la démonstration</span></a>` : ''}<p class="source-note">${p.visibility !== 'unpublished' ? 'Présentation fondée sur la documentation et les fichiers du dépôt.' : 'Présentation fondée sur le CV existant.'}</p></aside></div><div class="detail-other"><h2>Continuer l’exploration</h2><div class="project-grid">${projects.filter(x => x.id !== p.id).slice(0, 3).map(card).join('')}</div></div></main>${footer()}`;
}
export const notFound = () => `${header('/projets/')}<main class="container section" id="main"><p class="eyebrow">404 / PAGE INTROUVABLE</p><h1>Revenons aux projets.</h1><p class="not-found-text">Cette page n’est pas disponible.</p><a class="button primary" href="/">Revenir au portfolio</a></main>${footer()}`;

const pageIntro = (eyebrow, title, text) => `<div class="container page-intro"><p class="eyebrow">${e(eyebrow)}</p><h1>${title}</h1><p>${e(text)}</p></div>`;
export const collection = () => `${header('/projets/')}<main id="main" class="collection-page">${pageIntro('PROJETS', 'Du besoin.<br><span>À la réalisation.</span>', 'Embarqué, algorithmes et interfaces : découvrez le contexte de chaque projet, les techniques utilisées et les éléments disponibles.')}${projectSection(true)}${contactSection()}</main>${footer()}`;
export const about = () => `${header('/a-propos/')}<main id="main">${pageIntro('À PROPOS', 'Apprendre en faisant.<br><span>Comprendre en construisant.</span>', 'Je suis Rafelimanana Deraniaina, étudiant en Master 2 Objets Connectés à l’Université de Poitiers. Je recherche une alternance en systèmes embarqués et IoT.')}${profileSection()}${skillsSection()}${experienceSection()}${contactSection()}</main>${footer()}`;
export const resumePage = () => `${header('/cv/')}<main id="main" class="resume-page">${pageIntro('MES CV', 'Faisons connaissance.<br><span>Selon votre domaine.</span>', 'Deux CV pour explorer mon parcours selon vos besoins : systèmes embarqués et objets connectés, ou intelligence artificielle et traitement d’image.')}${cvSection()}${contactSection()}</main>${footer()}`;

const journeyPreview = () => `<section class="section container journey-preview" id="parcours"><div id="competences"><p class="eyebrow">MON PARCOURS</p><h2>De l’informatique<br><span>aux objets connectés.</span></h2></div><div><p>Ma formation à Poitiers et mes projets m’ont amené à travailler sur le logiciel, la visualisation 3D et les systèmes embarqués.</p><a class="text-link" href="/a-propos/">Découvrir mon parcours et mes compétences <span aria-hidden="true">›</span></a></div></section>`;
const storySection = () => `<section class="story-section" aria-labelledby="story-heading"><div class="container story-heading"><p class="eyebrow">DU CODE AU MONDE RÉEL</p><h2 id="story-heading">Une donnée ne raconte rien.<br><span>Avant qu’on lui donne du sens.</span></h2><p>La station météo résume bien ce que j’explore : relier un phénomène physique à une information utilisable.</p><button id="motion-toggle" class="motion-toggle" aria-pressed="false" hidden>Désactiver les animations</button></div><div class="container story-layout"><div class="story-visual" aria-hidden="true"><div class="story-halo"></div><div class="story-object">${artwork('station-meteo','story')}</div><div class="story-signal"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="story-visual-caption"><span>CAPTEUR → CODE → INFORMATION</span><span>Illustration conceptuelle</span></div></div><div class="story-steps"><article class="story-step" data-story-step="0"><span class="story-number">01 / OBSERVER</span><h3>Tout commence<br>par le réel.</h3><p>Température, humidité, pression : les capteurs de la station météo recueillent des données sur leur environnement.</p></article><article class="story-step" data-story-step="1"><span class="story-number">02 / TRAITER</span><h3>Le logiciel<br>fait le lien.</h3><p>Sur STM32, le code en C organise l’acquisition des mesures et coordonne les échanges avec les périphériques.</p></article><article class="story-step" data-story-step="2"><span class="story-number">03 / RESTITUER</span><h3>Une information<br>qui devient utile.</h3><p>Les mesures s’affichent sur l’écran tactile et peuvent être enregistrées au format CSV sur carte SD.</p><a class="text-link" href="/projets/station-meteo/">Explorer la station météo <span aria-hidden="true">›</span></a></article></div></div></section>`;
